### ISSUE TITLE
Leetcode Day 1: Contains Duplicate (2020-08)

### ISSUE THREAD

**Issue by thomasjpfan** [genvalen/testing#1]
## Problem

https://leetcode.com/problems/contains-duplicate/

## My Solution

```py
class Solution:
    def containsDuplicate(self, nums: List[int]) -> bool:
        seen = set()
        for num in nums:
            if num in seen:
                return True
            seen.add(num)
        return False
```

**Comment by genvalen** [comment]
testing:

class Solution:
    def containsDuplicate(self, nums: List[int]) -> bool:
        seen = set()
        for num in nums:
            if num in seen:
                return True
            seen.add(num)
        return False
